var express = require('express');
const router = express.Router();
const MeController = require('../app/controllers/MeController.js');
const checkAdmin = require('../app/middlewares/checkAdmin.js');
router.get('/create-product',checkAdmin, MeController.showCreatePage);
router.get('/stored/trash/products',checkAdmin, MeController.trashProducts);
router.get('/stored/products',checkAdmin, MeController.showProducts);
router.get('/stored/:id/edit',checkAdmin, MeController.showEditPage);
router.post('/products/handle-actions-form',checkAdmin, MeController.handleActionsForm);
router.put('/products/:id',checkAdmin, MeController.updateProduct);
router.patch('/products/:id/restore',checkAdmin, MeController.restoreProduct);
router.delete('/products/:id',checkAdmin, MeController.deleteProduct);
router.delete('/products/:id/hard-delete',checkAdmin, MeController.hardDeleteProduct);
router.post('/stored',checkAdmin, MeController.stored);
module.exports = router;
